import type { Metadata } from 'next';
import { RegistryProvider, UiKitProvider } from 'pro-ui';
import Provider from '@/_trpc/provider';
import '@/_styles/global.css';

export const metadata: Metadata = {
  title: 'Welcom Starter',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Provider>
          <UiKitProvider
            theme={{
              token: {
                colorPrimary: 'red',
              },
            }}
          >
            <RegistryProvider>{children}</RegistryProvider>
          </UiKitProvider>
        </Provider>
      </body>
    </html>
  );
}
